POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "REST Client for Codium seems handy",
    "important": true
}

# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {

# }